### ISSUE TITLE
optimize_from_memory returns zero byte image

### ISSUE THREAD

**Issue by RaiaN** [nfrasser/pyoxipng#5] opened 2022-12-14 19:14 UTC
Hey there!

Calling 
`optimize_from_memory(img_byte_arr, bit_depth_reduction=False, color_type_reduction=False, palette_reduction=False, grayscale_reduction=False)` results in 0 byte image. 

Doing just `optimize_from_memory(img_byte_arr)` works fine.

**Comment by RaiaN** [comment] 2022-12-14 19:30
Looking at `force` param. Is that by design?

force | Write to output even if there was no improvement in compression

**Comment by nfrasser** [comment] 2023-01-04 04:59
Hi @RaiaN , this is likely a bug with oxipng. I can't reproduce with the latest v7 so marking this as closed.

**Closed by nfrasser** 2023-01-04 04:59 UTC
